### ISSUE TITLE
macos support?

### ISSUE THREAD

**Issue by lin-ycv** [karamme/Parachute#2]
does this not support macos? can't find it in packagemanager on mac.

**Comment by lin-ycv** [comment]
manually copying the gha worked. I think you need to adjust your yak package, it's currently windows only.

**Comment by karamme** [comment]
Hi. I don't have access to a Mac. I did send the file to people to try for Apple, but I got no feedback back if that worked. So if you can verify that the plugin is running fine on Rhino for Mac, I can change the info for the packagemanager.

**Comment by lin-ycv** [comment]
Yes, as far as I can tell it works just fine on Mac.
